export {default as CoinDetailBuyIn} from './buyin';
export {default as CoinDetailSell} from './sell';
export {default as CoinDetailKline} from './kline';
export {default as CoinDetailKlineBar} from './klineBar';
export {default as CoinDetailMeta} from './meta';
export {default as CoinDetailNews} from './news';
export {default as CoinDetailAction} from './action';
export {default as CoinDetailSummary} from './summary';
export {default as CoinDetailFavorite} from './favorite';
